### ISSUE TITLE
Doesn't work in R5

### ISSUE THREAD

**Issue by ScienceofSpock** [cesarvandevelde/rhino-gears#1]
I downloaded the installer, ran it, which claims to have worked, but none of the commands are recognized. Everything results in "Unknown Command" I have tried the "EditPythonScript" workaround, and it doesn't work. What am I doing wrong?

**Comment by ScienceofSpock** [comment]
Little more digging. This plugin does not show up in my plugins list at all. I have run the installer TWICE. Both times it claimed to have installed successfully, but the plugin isn't actually installed and none of the commands work.

**Comment by ScienceofSpock** [comment]
Still looking for some help here. Is this even maintained anymore or is it just another abandoned project?

**Comment by cesarvandevelde** [comment]
Hi @ScienceofSpock, sorry for the late reply but life’s been busy and providing support for a free, pet-project plugin is not exactly a top priority. This plugin was written in Python because this is the only scripting language that works on both Rhino for Windows as well as Rhino for Mac. However, the scripting interface on Rhino 5 (win) has a number of annoying bugs, and there’s nothing I can do about it. McNeel has acknowledged these bugs, but will not fix them in v5.

That being said, please take a look at the following thread:
https://www.food4rhino.com/app/rhinogears?page=2#27777
Another user had a similar problem, and an employee from McNeel investigated the issue.
Be sure to select “Install just for me” when installing the plugin, otherwise nothing will be installed.

**Comment by ScienceofSpock** [comment]
Hey @cesarvandevelde The "just for me" option did the trick. I originally was following the instructions in the readme.md file, can you not put a blurb about the "just for me" option in there?

Anyway, thanks for the help!

**Comment by cesarvandevelde** [comment]
Glad to hear that solved the problem. I've updated the project readme accordingly.
